#!/bin/bash

set -o errexit
set -o pipefail

# GLOBALS
readonly WIP_PATH="$HOME/.wip"
readonly WIP_TMP="$HOME/.wip.tmp"
readonly CMD_LS="ls"
readonly CMD_ADD="add"
readonly CMD_RM="rm"
readonly CURRENT="$(pwd -P)"
readonly BASE="$(basename $CURRENT)"

# set signal trap
trap "rm -f $WIP_TMP" EXIT SIGINT SIGTERM

usage() {
  cat <<USAGE >&2

Usage: wip <command>

Commands:
-h/--help  -  show this message
ls         -  list
add        -  add current
rm         -  remove current
USAGE
}

main() {

  touch $WIP_PATH
  local exit_status=0
  local command="$1"
  shift

  if [[ -z $command ]] || [[ "$command" =~ -h|--help ]] ; then
    exit 1
  fi

  if ! type "wip_${command}" >/dev/null 2>&1 ; then
    usage
    exit 2
  fi

  eval "wip_${command}"
}

function wip_ls() {
  _sort
  echo -e "\nWIPs:"
  cat $WIP_PATH
  echo
}

_sort() {
  cat $WIP_PATH > $WIP_TMP
  cat $WIP_TMP | sort > $WIP_PATH
  rm -f $WIP_TMP
}

function wip_add() {
  if ! grep "$BASE" $WIP_PATH ; then
    echo "$BASE" >> $WIP_PATH
  fi
}

function wip_rm() {
  cat $WIP_PATH | awk "\$0 != \"$BASE\"" > $WIP_TMP
  cat $WIP_TMP > $WIP_PATH
  rm -f $WIP_TMP
}

main "$@"
